/**
 * OPROX Studio Phase 1 — Studio Drizzle Generator
 * Converts Studio Schema Models into valid TypeScript Drizzle ORM code.
 */

import { StudioSchemaModel, StudioSchemaTable } from './studioIr';

export function generateDrizzleTableCode(table: StudioSchemaTable): string {
  const tableNameVar = `${table.name.replace(/[^a-zA-Z0-9]/g, '_')}Table`;
  const columnsCode: string[] = [];

  for (const col of table.columns) {
    let colDef = '';
    const colName = col.name;

    switch (col.type) {
      case 'text':
        colDef = `text("${colName}")`;
        break;
      case 'integer':
        colDef = `integer("${colName}")`;
        break;
      case 'boolean':
        colDef = `boolean("${colName}")`;
        break;
      case 'timestamp':
        colDef = `timestamp("${colName}")`;
        break;
      case 'jsonb':
        colDef = `jsonb("${colName}")`;
        break;
      case 'uuid':
        colDef = `text("${colName}")`; // Standardized as text UUID in OPROX
        break;
      default:
        colDef = `text("${colName}")`;
    }

    if (col.isPrimaryKey) {
      colDef += '.primaryKey()';
    }
    if (col.isNullable === false && !col.isPrimaryKey) {
      colDef += '.notNull()';
    }
    if (col.isUnique) {
      colDef += '.unique()';
    }
    if (col.defaultValue) {
      if (col.defaultValue === 'now()') colDef += '.defaultNow()';
      else colDef += `.default("${col.defaultValue}")`;
    }

    columnsCode.push(`    ${col.name}: ${colDef},`);
  }

  return `export const ${tableNameVar} = pgTable(
  "${table.name}",
  {
${columnsCode.join('\n')}
  }
);

export type ${table.name.charAt(0).toUpperCase() + table.name.slice(1)}Row = typeof ${tableNameVar}.$inferSelect;`;
}

export function generateDrizzleSchemaCode(schemaModel: StudioSchemaModel): string {
  if (!schemaModel || !Array.isArray(schemaModel.tables) || schemaModel.tables.length === 0) {
    return `// OPROX Studio: No database tables defined in ERD schema model.`;
  }

  const tableBlocks = schemaModel.tables.map(generateDrizzleTableCode);

  return `import { pgTable, text, integer, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core';

/**
 * Auto-generated Drizzle ORM Schema
 * Generated by OPROX Studio Phase 1 Schema Builder
 */

${tableBlocks.join('\n\n')}
`;
}
