import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Sliders,
  Play,
  RotateCcw,
  BookOpen,
  Paperclip,
  Code2,
  Cpu,
  Layers,
  HelpCircle,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  FileText,
  PanelLeft,
  PanelRight,
  PanelBottom,
  Bot,
  Workflow,
  Brain,
  SlidersHorizontal
} from 'lucide-react';
import { PromptWorkspace } from './PromptWorkspace';
import { MultiAgentWorkspace } from './MultiAgentWorkspace';
import { TaskPipelinePanel } from './TaskPipelinePanel';
import { ContextMemoryPanel } from './ContextMemoryPanel';
import {
  ModelConfig,
  PromptTemplate,
  ContextItem,
  MemoryItem,
  AITaskItem,
  AgentMessage,
  AgentRole
} from '../../types';
import {
  DEFAULT_MODEL_CONFIG,
  PROMPT_TEMPLATES,
  INITIAL_CONTEXT_ITEMS,
  INITIAL_MEMORY_ITEMS,
  INITIAL_AI_TASKS,
  INITIAL_SWARM_TIMELINE
} from '../../data/aiOsData';

interface AiOperatingSystemProps {
  initialPrompt?: string;
  onLaunchIdeWithPrompt?: (prompt: string, title: string) => void;
  theme?: 'dark' | 'light';
}

export const AiOperatingSystem: React.FC<AiOperatingSystemProps> = ({
  initialPrompt = '',
  onLaunchIdeWithPrompt,
  theme = 'dark'
}) => {
  const isDark = theme === 'dark';

  // AI OS State
  const [modelConfig, setModelConfig] = useState<ModelConfig>(DEFAULT_MODEL_CONFIG);
  const [promptText, setPromptText] = useState<string>(
    initialPrompt || 'Build a multi-tenant authentication microservice with Drizzle PostgreSQL schema, Express API routes, Vitest tests, and Cloud Run deployment.'
  );

  const [templates, setTemplates] = useState<PromptTemplate[]>(PROMPT_TEMPLATES);
  const [contextItems, setContextItems] = useState<ContextItem[]>(INITIAL_CONTEXT_ITEMS);
  const [memoryItems, setMemoryItems] = useState<MemoryItem[]>(INITIAL_MEMORY_ITEMS);
  const [tasks, setTasks] = useState<AITaskItem[]>(INITIAL_AI_TASKS);
  const [messages, setMessages] = useState<AgentMessage[]>(INITIAL_SWARM_TIMELINE);

  const [isProcessing, setIsProcessing] = useState(false);
  const [isPipelineRunning, setIsPipelineRunning] = useState(false);

  // Panel Collapsible State
  const [showRightSidebar, setShowRightSidebar] = useState(true);
  const [showBottomPanel, setShowBottomPanel] = useState(true);
  const [layoutPreset, setLayoutPreset] = useState<'full' | 'prompt-focus' | 'swarm-focus'>('full');

  // Load layout from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem('oprox_ai_os_layout');
      if (saved) {
        const parsed = JSON.parse(saved);
        setShowRightSidebar(parsed.showRightSidebar ?? true);
        setShowBottomPanel(parsed.showBottomPanel ?? true);
        setLayoutPreset(parsed.layoutPreset ?? 'full');
      }
    } catch (e) {
      // ignore
    }
  }, []);

  const saveLayout = (newState: Partial<any>) => {
    try {
      const curr = { showRightSidebar, showBottomPanel, layoutPreset, ...newState };
      localStorage.setItem('oprox_ai_os_layout', JSON.stringify(curr));
    } catch (e) {
      // ignore
    }
  };

  const handleToggleContextItem = (id: string) => {
    setContextItems((prev) =>
      prev.map((item) => (item.id === id ? { ...item, isSelected: !item.isSelected } : item))
    );
  };

  const handleAddMemory = (key: string, value: string, category: any) => {
    const newItem: MemoryItem = {
      id: 'mem_' + Math.random().toString(36).substring(7),
      key,
      value,
      category,
      lastUpdated: 'Just now'
    };
    setMemoryItems((prev) => [newItem, ...prev]);
  };

  const handleSelectTemplate = (template: PromptTemplate) => {
    setPromptText(template.templateText);
  };

  const handleDispatchTask = async (role: AgentRole, text: string) => {
    setIsProcessing(true);

    try {
      const res = await fetch('/api/ai/agent-task', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentType: role,
          prompt: text || promptText,
          projectContext: 'OPROX Enterprise Swarm OS'
        })
      });

      const data = await res.json();

      const newMsg: AgentMessage = {
        id: 'msg_' + Math.random().toString(36).substring(7),
        agentRole: role,
        timestamp: new Date().toLocaleTimeString(),
        thought: data.thought || `Executing task for ${role}: "${text}"`,
        content: data.reviewNotes || `Completed routine: ${text}`,
        plan: data.plan || ['1. Analyze spec', '2. Synthesize code AST', '3. Validate types'],
        codeSnippet: data.codeSnippet || `// ${role} Output\nexport const ${role.toLowerCase()}Module = () => {\n  return "Generated by ${role}";\n};`
      };

      setMessages((prev) => [...prev, newMsg]);
    } catch (err) {
      console.error('Agent dispatch error:', err);
      const fallbackMsg: AgentMessage = {
        id: 'msg_' + Math.random().toString(36).substring(7),
        agentRole: role,
        timestamp: new Date().toLocaleTimeString(),
        thought: `[Fallback Local Engine] Executing task for ${role}: "${text}"`,
        content: `Completed routine: ${text}`,
        plan: ['1. Analyze spec', '2. Synthesize code AST', '3. Validate types'],
        codeSnippet: `// ${role} Output\nexport const ${role.toLowerCase()}Module = () => {\n  return "Generated by ${role}";\n};`
      };
      setMessages((prev) => [...prev, fallbackMsg]);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleRunSwarm = async () => {
    setIsProcessing(true);

    // Reset tasks status to pending then sequence them
    setTasks((prev) => prev.map((t) => ({ ...t, status: 'pending' })));

    const agentRoles: AgentRole[] = ['Planner', 'Architect', 'Coder', 'Reviewer', 'Tester', 'DevOps'];

    for (let i = 0; i < agentRoles.length; i++) {
      const role = agentRoles[i];
      // Mark task as in_progress
      setTasks((prev) =>
        prev.map((t, idx) => (idx === i ? { ...t, status: 'in_progress' } : t))
      );

      try {
        const res = await fetch('/api/ai/agent-task', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            agentType: role,
            prompt: promptText,
            projectContext: 'OPROX Autonomous Swarm Workflow'
          })
        });

        const data = await res.json();

        const newMsg: AgentMessage = {
          id: 'sw_' + Math.random().toString(36).substring(7),
          agentRole: role,
          timestamp: new Date().toLocaleTimeString(),
          thought: data.thought || `Swarm step ${i + 1}/6: Executing ${role} AST pass for prompt`,
          content: data.reviewNotes || `Agent ${role} finalized sub-routine successfully.`,
          plan: data.plan || [`Phase ${i + 1}: ${role} verification completed`],
          codeSnippet: data.codeSnippet || (i % 2 === 0 ? `// ${role} Stage Asset\nexport function run${role}Check() { return true; }` : undefined)
        };

        setMessages((prev) => [...prev, newMsg]);
      } catch (err) {
        console.error('Swarm step error:', err);
        const fallbackMsg: AgentMessage = {
          id: 'sw_' + Math.random().toString(36).substring(7),
          agentRole: role,
          timestamp: new Date().toLocaleTimeString(),
          thought: `Swarm step ${i + 1}/6: Executing ${role} AST pass for prompt`,
          content: `Agent ${role} finalized sub-routine successfully.`,
          plan: [`Phase ${i + 1}: ${role} verification completed`],
          codeSnippet: i % 2 === 0 ? `// ${role} Stage Asset\nexport function run${role}Check() { return true; }` : undefined
        };
        setMessages((prev) => [...prev, fallbackMsg]);
      }

      setTasks((prev) =>
        prev.map((t, idx) => (idx === i ? { ...t, status: 'completed' } : t))
      );
    }

    setIsProcessing(false);
  };

  const handleRunPipeline = async () => {
    setIsPipelineRunning(true);
    setTasks((prev) => prev.map((t) => ({ ...t, status: 'pending' })));

    for (let i = 0; i < tasks.length; i++) {
      setTasks((prev) =>
        prev.map((t, idx) => (idx === i ? { ...t, status: 'in_progress' } : t))
      );
      await new Promise((res) => setTimeout(res, 300));
      setTasks((prev) =>
        prev.map((t, idx) => (idx === i ? { ...t, status: 'completed' } : t))
      );
    }

    setIsPipelineRunning(false);
  };

  return (
    <div className="h-[calc(100vh-65px)] flex flex-col bg-slate-950 overflow-hidden text-slate-100">
      {/* Top Header Controls (Google AI Studio aesthetic) */}
      <div className="px-4 py-2 border-b border-slate-800 bg-slate-900 flex flex-wrap items-center justify-between gap-3 text-xs select-none">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 via-teal-500 to-indigo-600 flex items-center justify-center font-bold text-slate-950 shadow-md">
              <Bot className="w-4 h-4 stroke-[2.5]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-extrabold text-sm text-white tracking-wide">
                  OPROX AI Operating System
                </span>
                <span className="px-2 py-0.5 rounded text-[9px] font-bold font-mono bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  Google AI Studio Paradigm
                </span>
              </div>
              <p className="text-[10px] text-slate-400 font-mono">
                Multi-Agent Swarm • Autonomous Code Synthesis Engine
              </p>
            </div>
          </div>
        </div>

        {/* Layout Presets & Toggle Switches */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 p-0.5 rounded-xl border bg-slate-950 border-slate-800">
            {[
              { id: 'full', label: 'Full OS', icon: <Layers className="w-3.5 h-3.5" /> },
              { id: 'prompt-focus', label: 'Prompt Studio', icon: <Code2 className="w-3.5 h-3.5" /> },
              { id: 'swarm-focus', label: 'Swarm Focus', icon: <Bot className="w-3.5 h-3.5" /> }
            ].map((p) => (
              <button
                key={p.id}
                onClick={() => {
                  setLayoutPreset(p.id as any);
                  if (p.id === 'prompt-focus') {
                    setShowRightSidebar(false);
                    setShowBottomPanel(false);
                  } else if (p.id === 'swarm-focus') {
                    setShowRightSidebar(true);
                    setShowBottomPanel(true);
                  } else {
                    setShowRightSidebar(true);
                    setShowBottomPanel(true);
                  }
                }}
                className={`flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[11px] font-semibold cursor-pointer transition-all ${
                  layoutPreset === p.id
                    ? 'bg-slate-800 text-emerald-400 font-bold shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {p.icon}
                <span>{p.label}</span>
              </button>
            ))}
          </div>

          <div className="h-4 w-px bg-slate-800" />

          {/* Panel Visibility Buttons */}
          <div className="flex items-center gap-1">
            <button
              onClick={() => {
                const n = !showBottomPanel;
                setShowBottomPanel(n);
                saveLayout({ showBottomPanel: n });
              }}
              title="Toggle Tasks & Execution Pipeline Panel"
              className={`p-1.5 rounded-lg border cursor-pointer transition-all ${
                showBottomPanel
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                  : 'text-slate-400 border-slate-800 hover:text-slate-200'
              }`}
            >
              <PanelBottom className="w-4 h-4" />
            </button>

            <button
              onClick={() => {
                const n = !showRightSidebar;
                setShowRightSidebar(n);
                saveLayout({ showRightSidebar: n });
              }}
              title="Toggle Context & Memory Sidebar"
              className={`p-1.5 rounded-lg border cursor-pointer transition-all ${
                showRightSidebar
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                  : 'text-slate-400 border-slate-800 hover:text-slate-200'
              }`}
            >
              <PanelRight className="w-4 h-4" />
            </button>
          </div>

          {/* Launch in OPROX IDE button */}
          {onLaunchIdeWithPrompt && (
            <button
              onClick={() => onLaunchIdeWithPrompt(promptText, 'OPROX Generated Microservice')}
              className="flex items-center gap-2 px-3.5 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs shadow-lg shadow-emerald-500/20 transition-all cursor-pointer"
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>Open in OPROX IDE</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Workspace Body */}
      <div className="flex-1 grid grid-cols-12 overflow-hidden">
        
        {/* Left Column (Prompt Workspace + Multi-Agent Timeline) */}
        <div className={`h-full flex flex-col overflow-hidden ${
          showRightSidebar ? 'col-span-12 lg:col-span-9' : 'col-span-12'
        }`}>
          {/* Top Split: Prompt Studio & Multi-Agent Swarm Stream */}
          <div className={`grid grid-cols-1 lg:grid-cols-2 ${showBottomPanel ? 'h-[65%]' : 'h-full'} overflow-hidden border-b border-slate-800`}>
            {/* Prompt Studio */}
            <div className="h-full overflow-hidden border-r border-slate-800">
              <PromptWorkspace
                modelConfig={modelConfig}
                onChangeModelConfig={setModelConfig}
                promptText={promptText}
                onChangePromptText={setPromptText}
                templates={templates}
                onSelectTemplate={handleSelectTemplate}
                contextItems={contextItems}
                onRunSwarm={handleRunSwarm}
                isProcessing={isProcessing}
                theme={theme}
              />
            </div>

            {/* Multi-Agent Swarm Timeline */}
            <div className="h-full overflow-hidden">
              <MultiAgentWorkspace
                messages={messages}
                onDispatchTask={handleDispatchTask}
                isProcessing={isProcessing}
                theme={theme}
              />
            </div>
          </div>

          {/* Bottom Split: Tasks Queue & Execution Pipeline */}
          {showBottomPanel && (
            <div className="h-[35%] overflow-hidden">
              <TaskPipelinePanel
                tasks={tasks}
                isPipelineRunning={isPipelineRunning}
                onRunPipeline={handleRunPipeline}
                theme={theme}
              />
            </div>
          )}
        </div>

        {/* Right Sidebar (Context Panel, Memory Store, Attachments, Templates, History) */}
        {showRightSidebar && (
          <div className="col-span-12 lg:col-span-3 h-full overflow-hidden border-l border-slate-800">
            <ContextMemoryPanel
              contextItems={contextItems}
              onToggleContextItem={handleToggleContextItem}
              memoryItems={memoryItems}
              onAddMemory={handleAddMemory}
              templates={templates}
              onSelectTemplate={handleSelectTemplate}
              theme={theme}
            />
          </div>
        )}

      </div>
    </div>
  );
};
